### ISSUE TITLE
Get a session

### ISSUE THREAD

**Issue by RudyB** [spotify/SpotifyLogin#13]
Is there a way that the SpotifyLogin pod can work with the SPTAuthentication class from the iOS SDK. Specifically I am curious about setting the session in SPTAuthentication from Spotify Login.

**Comment by marmelroy** [comment]
SpotifyLogin is intended to eventually replace SPTAuthentication when using Swift and they don't work together. However, you are able to combine it with the playback classes from the iOS SDK.
