### ISSUE TITLE
Allow show_dialog to be false

### ISSUE THREAD

**Issue by arirawr** [spotify/SpotifyLogin#15]
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
`show_dialog` is hardcoded to true. It should be able to be set by the developer.

### Versions
1.0.6

### Severity
Minor

**Comment by arirawr** [comment]
I'll get around to developing this over the weekend if @marmelroy thinks it's a good idea :)

**Comment by marmelroy** [comment]
Sounds good @arirawr
