### ISSUE TITLE
Need queryScheme to check canOpenURL

### ISSUE THREAD

**Issue by onmyway133** [spotify/SpotifyLogin#2]
Hi, I'm reading the source code https://github.com/spotify/SpotifyLogin/blob/master/Sources/SpotifyLoginPresenter.swift, this line

```swift
UIApplication.shared.canOpenURL(appAuthenticationURL)
```

but as iOS 9+, there is new requirement https://useyourloaf.com/blog/querying-url-schemes-with-canopenurl/ that `LSApplicationQueriesSchemes` is needed.

I think we should state this in the README

**Comment by marmelroy** [comment]
You're right @onmyway133. Good find! Will update...

**Comment by marmelroy** [comment]
Fixed. Thanks again @onmyway133.
