### ISSUE TITLE
"If your app is meant for commercial production usage, SpotifyLogin can NOT be used."

### ISSUE THREAD

**Issue by mph070770** [spotify/SpotifyLogin#25]
We would like to use this to provide single sign-on and token creation for an app we're developing. Any reason why we can't?

**Comment by jdstregz** [comment]
I am also curious about this. It's extremely difficult to get the single sign-on working using the side server way, this would make the process much easier.

**Comment by tomaculum** [comment]
Is this quoted text a restriction or a warning? Since this project does have the Apache-2.0 license I think it is a warning because otherwise you should change the license to a much more restrictive. Especially since the Apache-2.0 license permits commercial usage.

**Comment by arirawr** [comment]
Hey there!

For production usage you should set up your own server and use the Authorization Code flow for OAuth, which is more secure as it keeps your client secret safe on the backend. The SpotifyLogin framework is intended for rapid prototyping. You can check out this token swap service as an example of how to set this up: https://github.com/bih/spotify-token-swap-service
