### ISSUE TITLE
Example project crashing because of missing resources

### ISSUE THREAD

**Issue by hugolundin** [spotify/SpotifyLogin#3]
## Description
When trying to run the example project, it crashes. 

```swift
self.setImage(UIImage(named: "spotifylogo-32.png",
                              in: Bundle(for: SpotifyLoginButton.self),
                              compatibleWith: nil)!
```
This line returns `nil` for me. 

### Versions
Xcode 9 Beta 6 on macOS Sierra with latest
available version of iOS in the simulator

### Severity
Major, since the only example usage of SpotifyLogin does not work. 

## Steps to Reproduce
1. Download repository
2. Run `pod install`  inside the example project folder to install dependencies from CocoaPods
3. Build and run example project

### Actual behaviour
The line described above returns `nil`, hence the application crashes.

**Comment by marmelroy** [comment]
Thanks @hugolundin. Indeed, the resources were missing from the pod spec. This is now fixed with release 0.1.2. 

Thanks a lot for reporting.
