### ISSUE TITLE
Change BPM value of Spotify Song Swift

### ISSUE THREAD

**Issue by ghost** [spotify/SpotifyLogin#33]
I am trying to build an application that plays Spotify songs. I am really confused about how to change BPM(Beats Per Minute,) value of Spotify songs.
First Step: Login through Spotify.
Second Step: Get Current user all album.
Third Step: get album track.
Last Step: play track.
I have done All step with Spotify Delegates. but I want to change the BPM value of the track.
Can someone please explain to me how to change the BPM value?

**Comment by tomaculum** [comment]
Hi shamdass,
This is a framework for authenticating with the Spotify API and not a Web API wrapper.
The [audio features endpoint](https://developer.spotify.com/documentation/web-api/reference/tracks/get-audio-features/) only allows GET requests therefore it is not possible to override the BPM (`tempo`) values provided by Spotify. 
If there is something wrong with the way the `tempo` values are calculated, please open an issue in the dedicated [Web API repository](https://github.com/spotify/web-api).

**Comment by ghost** [comment]
Hello @tomaculum, 
Thank you for your reply. I know this is a framework for authenticating with the Spotify API and not a Web API wrapper. but i have little confusion if there is only GET only property then some other application's change Spotify BPM. Is there any special paid service provided by Spotify ya any third party doing this?

**Comment by tomaculum** [comment]
Do you want to change the tempo attribute of the web API or change the playback speed on your device?
Unfortunately I don’t know if there is such a paid service or any third party provider.

**Comment by ghost** [comment]
Yes, I want to change playback speed of Spotify Song. Is there any way or any  web API through  change playback speed of Spotify song.

**Comment by tomaculum** [comment]
If there is no way to change playback speed with the [iOS-sdk](https://github.com/spotify/ios-sdk), you need to modify the playback somehow on your device like probably override some methods of the playback classes.
This is clearly no issue with the Spotify Login framework, therefore please ask this question on stackoverflow with the `spotify` tag.

**Comment by ghost** [comment]
Thank you for your reply @tomaculum 
Okay i will post this on Stackoverflow with the spotify tag. give me some suggestion how to change playback speed. Because  I've tried to change or  override playback classes but no results yet.
